name: Run Tests Workflow

on:
  # Only trigger the action for every change of the branch within a PR to master
  pull-request:
    branches:
      - master
  # or trigger manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t valix07/frontend -f ./Dockerfile.dev .
      - run: docker run -e CI=true valix07/frontend npm run test
