name: Test Workflow
on:
  pull-request:
    branches:
      - master
    paths:
      - ".github/workflows/test.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t valix07/frontend -f ./Dockerfile.dev .
      - run: docker run -e CI=true valix07/frontend npm run test
